# version: ‘3’

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/zz/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/zz/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

# docker build srcs/requirements/mariadb -t mariadb -> build une image depuis le Dockerfile en lui donnant un nom
# docker run -it nginx / docker run -d nginx -> run un container en se basant sur l'image build, -it pour interagir avec, -d pour le run en background 
# docker ps -> liste les running containers
# docker stop [id] -> stop un running container
# docker rm [id] -> remove a container
# docker rmi [id] -> remove an image
# docker exec [id] -> exec a cmd in a running container (-d)
# docker logs [id] -> see logs

# docker compose -f docker-compose.yml up -d --build -> compose les container ensemble
# docker compose down / docker compose down -v
#https://github.com/Forstman1/inception-42/tree/main?tab=readme-ov-file#what-are-the-most-common-commands-are-used-in-docker-compose-


# docker rm -vf $(docker ps -aq) -> supprime tout

# Other commands : docker volume ps